#!/usr/bin/env bash
#
# Periodically check if specified user is logging in and 
# send notification email
#
# Run this script once or upon login
#
# usage: 
#     hayate TARGET RECIPIENT_EMAIL
# example:
#     hayate watched_user admin@example.com

username="$1"
recipient="$2"
usage='usage: hayate TARGET RECIPIENT_EMAIL'
[ $# -lt 2 ] && { echo "$usage" >&2; exit 1; }
tmprc="/tmp/hayate.rc"
session='hayate-session'
sleeptime=120
cat > "$tmprc" <<EOF
while true
do
    if who | grep '$username' > /dev/null
    then
        who | mutt -s "WARNING: Watched user logging in on $(hostname)" $recipient
        sleep $sleeptime
    else
        sleep 2
    fi
done
EOF
# Remove existing sessions
screen -ls "$session" | grep "$session" > /dev/null && screen -X -S "$session" quit
screen -dmS "$session" bash "$tmprc"
