#!/usr/bin/env bash
#
# Periodically check if specified user is logging in and
# send notification email
#
# Run this script once or upon login
#
# usage:
#     hayate TARGET RECIPIENT_EMAIL
# example:
#     hayate watched_user admin@example.com

USERNAME="$1"
RECIPIENT="$2"
USAGE='usage: hayate TARGET RECIPIENT_EMAIL'
[ $# -lt 2 ] && { echo "$USAGE" >&2; exit 1; }
TMPRC="/tmp/hayate.rc"
SESSION='hayate-session'
SLEEPTIME=120
cat > "$TMPRC" <<EOF
while true
do
    if who | grep '$USERNAME' > /dev/null
    then
        { who; echo; w; } | mutt -s "WARNING: Watched user logging in on $(hostname)" $RECIPIENT
        sleep $SLEEPTIME
    else
        sleep 2
    fi
done
EOF
# Remove existing sessions
screen -ls "$SESSION" | grep "$SESSION" > /dev/null && screen -X -S "$SESSION" quit
screen -dmS "$SESSION" bash "$TMPRC"
